import { Component, OnInit } from '@angular/core';
import { PlayerService } from '../player.service';
import { FirebaseListObservable } from 'angularfire2/database';
import { Router } from '@angular/router';

@Component({
  selector: 'app-player-list',
  templateUrl: './player-list.component.html',
  styleUrls: ['./player-list.component.css'],
  providers: [PlayerService]
})
export class PlayerListComponent implements OnInit {

  // players: FirebaseListObservable<any[]>;
  constructor(private router: Router, private playerService: PlayerService) { }

  ngOnInit() {
    // this.players = this.playerService.getPlayers();
    console.log("player-list component" + this.players);
  }
  players = [ /*83 players */
    "Schwarber",
    "Rizzo",
    "Abreu",
    "Nolan",
    "Ichiro",
    "Manny",
    "Mookie",
    "Trout",
    "Allen, Dwayne",
    "Allen, Ryan",
    "Andrews, David",
    "Atkins, John",
    "Bentley, Ja'Whaun",
    "Berrios, Braxton",
    "Seager, Corey",
    "Bolden, Brandon",
    "Bowanko, Luke",
    "Brady, Tom",
    "Britt, Kenny",
    "Brown, Malcom",
    "Brown, Trent",
    "Burkhead, Rex",
    "Butler, Adam",
    "Cannon, Marcus",
    "Cardona, Joe",
    "Chung, Patrick",
    "Clayborn, Adrian",
    "Crossen, Keion",
    "Croston, Cole",
    "Davis, Keionta",
    "Dawson, Duke",
    "Develin, James",
    "Dorsett, Phillip",
    "Ebner, Nate",
    "Edelman, Julian",
    "Roller, Justin",
    "Etling, Danny",
    "Ferentz, James",
    "Flowers, Marquis",
    "Flowers, Trey",
    "Gillislee, Mike",
    "Gilmore, Stephon",
    "Gostkowski, Stephen",
    "McNamara, Jimmy",
    "Grigsby, Nicholas",
    "Grissom, Geneo",
    "Gronkowski, Rob",
    "Guy, Lawrence",
    "Harmon, Duron",
    "Harris, Trent",
    "Herron, Frank",
    "Hightower, Donta",
    "Hill, Jeremy",
    "Hogan, Chris",
    "Santos, Verna",
    "Hollister, Cody",
    "Hollister, Jacob",
    "Hoyer, Brian",
    "Izzo, Ryan",
    "Jackson, Jc",
    "Jelks, Andrew",
    "John, Ulrick",
    "Jones, Cyrus",
    "Jones, David",
    "Jones, Jonathan",
    "Karras, Ted",
    "King, Brandon",
    "King, Jason",
    "Langi, Harvey",
    "Lee, Eric",
    "Lewis, Ryan",
    "Mason, Shaq",
    "Tumbleposwki, Dave",
    "Matthews, Jordan",
    "McCarron, Riley",
    "McCourty, Devin",
    "McCourty, Jason",
    "Michel, Sony",
    "Mitchell, Malcolm",
    "Moore, An",
    "Niklas, Troy",
    "Patterson, Cordarrelle",
    "Lupton, Andrew",
    "Richards, Jordan",
    "Rivers, Derek",
    "Roberts, Elandon",
    "Rowe, Eric",
    "Sam, Christian"
  ];
}
